services:
  gateway:
    image: nginx
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      -  keystore
      - generate_key
      - sign
  generate_key:
    build:
      context: ./key_generator_service
      tags:
        - "hackyeah-key_generator:latest"
    ports:
      - 8001:80
    environment:
      - KEYSTORE_URL = "http://keystore:80/v1/keys"
  sign:
    build:
      context: ./sign
      tags:
        - "hackyeah-sign:latest"
    ports:
      - 8000:80
    environment:
     - KEYSTORE_URL = "http://keystore"
  #backend/asym-crypto:
  #  build:
  #    context: ./backend/asymm-crypto
  keystore:
    environment:
    - LOGGING__LOGLEVEL__DEFAULT=Trace
    - HACKYEAH__LOGSENSITIVE=true
    build: 
      context: ./backend/keystore
      tags:
        - "hackyeah-keystore:latest"
    volumes:
      - hackyeah-keystore:/data
    ports:
      - 5000:80
  backend-asymm-crypto:
    environment:
    - LOGGING__LOGLEVEL__DEFAULT=Trace
    - HACKYEAH__KEYSTORE=http://keystore:80/
    - HACKYEAH__TAG=ZW16aTA3NjctaGFja3llYWg=
    image: hackyeah-asymm-crypto:latest
    build: ./backend/asymm-crypto
    ports:
    - 5001:80
volumes:
  hackyeah-keystore:
