services:
  gateway:
    image: nginx
    ports:
     - "8080:80"
    environment:
     - NGINX_PORT=80
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
  generate_key:
    build:
      context: ./key_generator_service
      dockerfile: ../sign/Dockerfile
      tags:
        - "hackyeah-key_generator:latest"
    ports:
      - 8000
  sign:
    build:
      context: ./sign
      tags:
        - "hackyeah-sign:latest"
    ports:
      - 8000
  #backend/asym-crypto:
  #  build:
  #    context: ./backend/asymm-crypto
  keystore:
    build: 
      context: ./backend/keystore
      tags:
        - "hackyeah-keystore:latest"
    volumes:
      - hackyeah-keystore:/data
    ports:
      - 5000:80
volumes:
  hackyeah-keystore:
