// <auto-generated />
using System;
using HackYeah.Backend.Keystore.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HackYeah.Backend.Keystore.Data.Migrations
{
    [DbContext(typeof(KeystoreContext))]
    [Migration("20230930192837_UniqueName")]
    partial class UniqueName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.11");

            modelBuilder.Entity("HackYeah.Backend.Keystore.Data.DbCryptoKeyMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<byte[]>("PrivateKey")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("priv");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("pub");

                    b.Property<uint>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pkey_key_id");

                    b.HasAlternateKey("Name")
                        .HasName("ukey_key_name");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_key_name");

                    b.HasIndex("Size")
                        .HasDatabaseName("ix_key_size");

                    b.HasIndex("Type")
                        .HasDatabaseName("ix_key_type");

                    b.ToTable("keys", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
